schema_version: 1

context:
  name: pycomposefile
  version: 0.0.32

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pycomposefile-${{ version }}.tar.gz
  sha256: a355d515c4c4ff92ee5a16590de8b367a3be4827046592d0870f8cb6ac4a6e34

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml

tests:
  - python:
      imports:
        - pycomposefile
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Structured deserialization of Docker Compose files.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/smurawski/pycomposefile

extra:
  recipe-maintainers:
    - janjagusch
